import streamlit as st

st.title("AcaPilot")
st.write("Welcome to your personalized AI mentor that can help you study during your school semester")
st.write("You are getting closer to final exam, why don't we started by clicking the button GET STARTED")
    
    # Initialize session state
    
    # Show features
st.subheader("Features")
st.write("""
    - 📚 **Learning Roadmap**: Follow a structured learning path tailored to your goals generated by our AI agent
         
    - 🧪 **Unlimited Interactive Quizzes and Exams**: Test your knowledge with quizzes and get instant feedback based on your documents
         
    - 📖 **Learning Resources**: Access curated resources to support your learning journey
         
    - 🎁 **Reward**: Get some additonal perks including membership/gift cards
         
    - 💬 **AI Chat Support**: Get help from our AI tutor anytime
""")


start = st.button("Get started!")

if start:
    st.switch_page("pages/dashboard.py")


